<div id="fb-root"></div>
<script type="text/javascript">
(
function(d, s, id)
{
    var js, fjs = d.getElementsByTagName(s)[0];

    if (d.getElementById(id)) {
	    return;
    }

    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div class="hero-unit">
    <h1>SABE WEB</h1>
    <p>Sistema de gerenciamento escolas</p>
    <p><a class="btn btn-primary btn-large" href="<?php echo $this->getBaseUrl(); ?>/about">Maiores Informações &raquo;</a></p>
</div>

